### ISSUE TITLE
Need Code Contributors for Hacktoberfest 2021. Just add any algorithm you want.

### ISSUE THREAD

**Issue by ascii5833** [aahancharak/Data-Structures#2]
**Types of algorithms supported:`**

- Generic Algorithms
- Cryptographic Algorithms

**Comment by jodahoney** [comment]
@pokemonChampion5833 Would you like me to create an issue first regarding the algorithm/leetcode type problem and solution and then you assign it to me, or just make a direct pull request?

**Comment by pokemonChampion5833** [comment]
Sure.

**Comment by ascii5833** [comment]
> @pokemonChampion5833 Would you like me to create an issue first regarding the algorithm/leetcode type problem and solution and then you assign it to me, or just make a direct pull request?

Sure. Any contribution is appreciated.
